// Exercise library. Built from widely taught, low-risk voice-pedagogy tools: semi-occluded vocal
// tract (SOVT) work such as lip trills, straw phonation and "ng" sirens; Seth Riggs-style
// consonant-vowel patterns ("nay", "gug", "mum") for crossing the passaggio; messa di voce; and
// vowel modification. Each exercise is written as short imperative steps a singer can follow alone.
//
// Pattern conventions (see Exercise['pattern'] in src/types.ts and audio/tones.ts): steps are
// semitones from the start note, which is `startOffsetFromPassaggio` semitones from the low edge
// of the user's passaggio. Starting offsets are chosen so the first round sits comfortably below
// the passaggio and later rounds (stepping up) cross into it without going far above it. Scales
// and arpeggios play one beat per step; a 'sustain' step lasts four beats; a 'siren' glides
// steps[0] -> steps[1] -> steps[0] over four beats.

import type { Exercise } from '../types';

const MAJOR_FIVE_TONE = [0, 2, 4, 5, 7, 5, 4, 2, 0];
const OCTAVE_ARPEGGIO = [0, 4, 7, 12, 7, 4, 0];

export const EXERCISES: Exercise[] = [
  {
    id: 'lip-trill-siren',
    name: 'Lip-trill sirens',
    goal: 'Glide through the passaggio on a lip trill so chest and head voice connect without a break or a jump in volume.',
    helps: ['mixInUpperRange', 'chestInUpperRange', 'loudnessClimbDbPerSemitone', 'flipsPerMinute'],
    steps: [
      'Rest two fingertips lightly on your cheeks beside the corners of your mouth and blow a relaxed "brrr" through loose lips.',
      'Add easy voice to the trill on a comfortable low note.',
      'Glide up to the top of the pattern and back down in one breath, like a slow siren.',
      'Keep the trill going at the same speed the whole way. If it stalls, use a little less voice, not more push.',
      'Let the voice change gear near the passaggio on its own; do not force it to stay in chest.',
    ],
    durationMin: 3,
    pattern: { kind: 'siren', steps: [0, 12], bpm: 60, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 5 },
    cautions: ['If lip trills will not keep going, use a tongue trill or a straw instead.'],
  },
  {
    id: 'straw-phonation-slides',
    name: 'Straw phonation slides',
    goal: 'Balance airflow against how firmly your vocal folds meet, using a semi-occluded vocal tract (SOVT: sound through a narrowed opening such as a straw), so high notes need less effort.',
    helps: ['loudnessClimbDbPerSemitone', 'mixInUpperRange', 'breathiness', 'rasp'],
    steps: [
      'Seal your lips around a drinking straw. A regular straw is easiest; a narrow coffee stirrer gives more back-pressure.',
      'Hum through the straw on a comfortable note. You should feel a gentle buzz and back-pressure, with no air leaking from your nose.',
      'Slide up about an octave and back down slowly, keeping the airflow steady.',
      'Sing a phrase of your song through the straw, keeping the same ease.',
      'Take the straw away and sing the phrase once more, copying that feeling.',
    ],
    durationMin: 4,
    pattern: { kind: 'siren', steps: [0, 12], bpm: 50, startOffsetFromPassaggio: -7, stepUpSemitones: 2, repetitions: 4 },
    cautions: ['Keep it gentle: no puffed cheeks and no pushing air hard through the straw.'],
  },
  {
    id: 'ng-siren',
    name: '"Ng" sirens',
    goal: 'Find a light, forward, connected sound through the break, with the back of the tongue resting against the soft palate.',
    helps: ['mixInUpperRange', 'headInUpperRange', 'brightness', 'flipsPerMinute'],
    steps: [
      'Say "sing" and hold the final "ng": the back of your tongue touches the soft palate and the sound comes through your nose.',
      'On that "ng", siren from a comfortable low note up over your passaggio and back down.',
      'Keep it quiet and buzzy in the front of your face, and do not let it get louder as it rises.',
      'If the voice breaks, go through that spot more slowly and more lightly.',
      'Finish by opening the "ng" into "ah" at the top of the siren without losing the buzz.',
    ],
    durationMin: 3,
    pattern: { kind: 'siren', steps: [0, 14], bpm: 60, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 5 },
  },
  {
    id: 'nay-bright-mix',
    name: '"Nay" five-tone scales',
    goal: 'Build a bright, forward mix with vocal folds that meet firmly but easily: the buzzy core of a pop chorus.',
    helps: ['brightness', 'mixInUpperRange', 'breathiness', 'chestInUpperRange'],
    steps: [
      'Say "nay" in a slightly bratty, nasal way, like imitating a whiny child.',
      'Sing it on 1-2-3-4-5-4-3-2-1 of the scale, one "nay" per note.',
      'Keep the volume moderate and the same on every note; let the brightness do the work.',
      'Above your passaggio, narrow the "ay" slightly toward "eh" instead of spreading it.',
      'Once it feels easy, sing the scale on "nyah", then sing a line of your song with the same buzz.',
    ],
    durationMin: 4,
    pattern: { kind: 'scale', steps: MAJOR_FIVE_TONE, bpm: 132, startOffsetFromPassaggio: -5, stepUpSemitones: 1, repetitions: 6 },
    cautions: ['It should feel buzzy, not tight. If your throat squeezes, make it quieter and less nasal.'],
  },
  {
    id: 'gee-gug-connected-mix',
    name: '"Gee" and "gug" arpeggios',
    goal: 'Keep a connected mix through the passaggio without flipping into falsetto or pulling chest voice up.',
    helps: ['mixInUpperRange', 'flipsPerMinute', 'headInUpperRange', 'chestInUpperRange'],
    steps: [
      'Sing "gug" (the "u" as in "up") with a slightly dopey sound; the "uh" vowel helps keep the larynx from rising.',
      'Sing 1-3-5-8-5-3-1 on repeated, lightly detached "gug"s.',
      'At the top, keep the "uh" narrow and do not let it get louder.',
      'Alternate rounds on "gee" (hard "g") for a brighter version.',
      'If the top flips into a breathy falsetto, add a little more "g" bite. If it strains, sing it quieter.',
    ],
    durationMin: 4,
    pattern: { kind: 'arpeggio', steps: OCTAVE_ARPEGGIO, bpm: 108, startOffsetFromPassaggio: -9, stepUpSemitones: 1, repetitions: 4 },
    cautions: ['Stop the pattern once the top notes feel effortful; you don\'t need to finish every round.'],
  },
  {
    id: 'mum-five-tone',
    name: '"Mum" five-tone scales',
    goal: 'Climb without getting louder: the "m" keeps the sound easy and the "uh" stops it spreading.',
    helps: ['loudnessClimbDbPerSemitone', 'mixInUpperRange', 'chestInUpperRange', 'pitchAccuracyCents'],
    steps: [
      'Sing "mum" on each note of 1-2-3-4-5-4-3-2-1.',
      'Let the lips close gently on each "m" and feel the buzz there.',
      'Make the top note the same volume as the bottom note.',
      'Let the voice lighten as you go up rather than holding on to the weight of the bottom note.',
      'Slow down if any note jumps out louder than the rest.',
    ],
    durationMin: 3,
    pattern: { kind: 'scale', steps: MAJOR_FIVE_TONE, bpm: 120, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 6 },
  },
  {
    id: 'octave-slide-wee-oo',
    name: 'Octave slides on "wee" and "oo"',
    goal: 'Practise a light, easy route into head voice or falsetto and back, so high notes float instead of push.',
    helps: ['headInUpperRange', 'mixInUpperRange', 'flipsPerMinute', 'loudnessClimbDbPerSemitone', 'brightness'],
    steps: [
      'Start on a comfortable note on "wee".',
      'Slide up an octave on "wee", getting lighter as you go, then slide back down.',
      'Repeat on "oo" with rounded lips and a loose jaw.',
      'Let the top note be light and floaty; it is fine for it to be quieter than the bottom.',
      'Aim for one smooth glide. Small bumps are normal at first.',
    ],
    durationMin: 3,
    pattern: { kind: 'siren', steps: [0, 12], bpm: 60, startOffsetFromPassaggio: -5, stepUpSemitones: 1, repetitions: 5 },
  },
  {
    id: 'messa-di-voce',
    name: 'Messa di voce (swell and fade)',
    goal: 'Control dynamics on one note: grow from soft to fuller and back without the tone cracking, wobbling or changing pitch.',
    helps: ['dynamicRangeDb', 'loudnessClimbDbPerSemitone', 'mixInUpperRange', 'pitchAccuracyCents', 'vibratoPresence', 'softOnsetRatio'],
    steps: [
      'Start a comfortable note just below your passaggio very softly on "ah" or "oh", with an easy onset.',
      'Over about four seconds, let it grow to a medium-full sound, never a shout.',
      'Over the next four seconds, fade back to the same soft level.',
      'Keep the pitch steady the whole way; check with the tuner or the played note.',
      'Move up a semitone and repeat. Stop before the loudest point feels like effort.',
    ],
    durationMin: 4,
    pattern: { kind: 'sustain', steps: [0], bpm: 30, startOffsetFromPassaggio: -4, stepUpSemitones: 1, repetitions: 5 },
    cautions: ['The loudest point should still feel easy. If your throat tightens, cap the swell lower.'],
  },
  {
    id: 'falsetto-bridge-down',
    name: 'Bridge down from falsetto on "hoo"',
    goal: 'Blend head voice down into mix so the registers meet instead of switching abruptly.',
    helps: ['mixInUpperRange', 'headInUpperRange', 'flipsPerMinute', 'breathiness'],
    steps: [
      'Start the top note in a light falsetto on "hoo", quiet and easy.',
      'Sing down 5-4-3-2-1 without an abrupt gear change, carrying some of the light quality down with you.',
      'As you descend, let the tone firm up gradually, as if "hoo" slowly turns into "who".',
      'Keep the vowel narrow and the volume nearly the same all the way down.',
      'Start each round a semitone higher.',
    ],
    durationMin: 3,
    pattern: { kind: 'scale', steps: [7, 5, 4, 2, 0], bpm: 96, startOffsetFromPassaggio: -2, stepUpSemitones: 1, repetitions: 5 },
  },
  {
    id: 'level-volume-scale',
    name: 'Level-volume octave scales',
    goal: 'Resist the urge to get louder as you climb, which is the most common way chest voice gets pushed up.',
    helps: ['loudnessClimbDbPerSemitone', 'chestInUpperRange', 'mixInUpperRange'],
    steps: [
      'Record yourself, or watch the level meter, while you sing.',
      'Sing a one-octave major scale up and down on "ah" or "uh" at a medium-soft level.',
      'Keep the top note as loud as the bottom note, no louder: let it get lighter instead.',
      'Narrow the vowel toward "uh" on the top three notes.',
      'Play it back. If the top jumps out, repeat at a quieter level.',
    ],
    durationMin: 3,
    pattern: {
      kind: 'scale',
      steps: [0, 2, 4, 5, 7, 9, 11, 12, 11, 9, 7, 5, 4, 2, 0],
      bpm: 100,
      startOffsetFromPassaggio: -9,
      stepUpSemitones: 1,
      repetitions: 4,
    },
  },
  {
    id: 'vowel-narrowing',
    name: 'Vowel narrowing through the passaggio',
    goal: 'Adjust vowels as the pitch rises so high notes stay balanced instead of spreading or pulling chest up.',
    helps: ['chestInUpperRange', 'mixInUpperRange', 'loudnessClimbDbPerSemitone', 'brightness'],
    steps: [
      'Sing 1-3-5-8-5-3-1 on "ah".',
      'From the fifth upward, let "ah" drift toward "uh" (as in "up"); on other vowels, "ay" drifts toward "eh" and "ee" toward "ih".',
      'Keep the jaw relaxed. It can drop a little as you go up, but keep the lips from spreading into a wide smile.',
      'To a listener it should still sound like "ah"; the change is small.',
      'Apply the same narrowing to the highest words of your song.',
    ],
    durationMin: 3,
    pattern: { kind: 'arpeggio', steps: OCTAVE_ARPEGGIO, bpm: 96, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 3 },
    cautions: ['Stop the pattern once the top notes feel effortful; you don\'t need to finish every round.'],
  },
  {
    id: 'aspirate-onsets',
    name: 'Aspirate onsets on "h"',
    goal: 'Practise the soft, airy phrase start of intimate R&B verses.',
    helps: ['softOnsetRatio', 'breathiness', 'dynamicRangeDb'],
    steps: [
      'Sigh out a relaxed "h" and let the tone appear just after it: "h-ah", "h-oo", "h-ee".',
      'Keep it quiet. The "h" should be audible but short.',
      'Sing three separate notes, starting each with "h".',
      'Then sing a phrase of your song with a quiet "h" before the first word.',
      'Keep the air light; do not dump all your breath on the first note.',
    ],
    durationMin: 3,
    pattern: { kind: 'scale', steps: [0, 2, 4], bpm: 60, startOffsetFromPassaggio: -7, stepUpSemitones: 2, repetitions: 4 },
    cautions: ['Very airy singing dries the voice. Sip water and alternate with clearer tone.'],
  },
  {
    id: 'balanced-onsets',
    name: 'Balanced onsets',
    goal: 'Start notes with air and tone together, neither breathy nor with a glottal click.',
    helps: ['softOnsetRatio', 'breathiness', 'pitchAccuracyCents'],
    steps: [
      'Say "uh-oh" and notice the small catch before "oh": that is a glottal onset. Now say "hoh": that is an aspirate onset.',
      'Aim between them: start "ah" so the sound begins exactly as the air moves, with no "h" and no click.',
      'Sing short, separate notes on "ah", "ee" and "oh", each started this way.',
      'Hear the pitch in your head before you start, so the note begins in tune.',
      'Use the same onset on the first word of each phrase of your song.',
    ],
    durationMin: 3,
    pattern: { kind: 'arpeggio', steps: [0, 4, 7, 4, 0], bpm: 66, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 4 },
    cautions: ['Avoid hard glottal clicks: repeated forcefully, they are hard on the vocal folds.'],
  },
  {
    id: 'vibrato-pulses',
    name: 'Vibrato pulses',
    goal: 'Build a free vibrato by pulsing between two neighbouring pitches and letting the pulses speed up into natural vibrato.',
    helps: ['vibratoPresence', 'vibratoRateHz', 'vibratoExtentCents'],
    steps: [
      'On "ah" at a comfortable pitch, alternate slowly and smoothly between the note and the semitone above.',
      'Keep the pulses connected, and make them without moving your jaw or tongue and without pulsing your stomach.',
      'Gradually make the pulses faster and smaller until they blur into a wobble of about five to six per second.',
      'Then stop controlling it and just sustain the note, letting the vibrato carry on by itself.',
      'If it turns into a fast, tight flutter, relax and start again more slowly.',
    ],
    durationMin: 4,
    pattern: { kind: 'scale', steps: [0, 1, 0, 1, 0, 1, 0, 1, 0], bpm: 144, startOffsetFromPassaggio: -5, stepUpSemitones: 1, repetitions: 3 },
  },
  {
    id: 'straight-then-vibrato',
    name: 'Straight tone, then vibrato',
    goal: 'Choose when vibrato appears: hold notes straight, then release it late, as pop and soul singers do at phrase ends.',
    helps: ['vibratoPresence', 'vibratoExtentCents', 'vibratoRateHz', 'pitchAccuracyCents'],
    steps: [
      'Sustain a note on "oo" with a completely straight tone, no wobble, for about four seconds.',
      'Keep the same volume, stop holding the note still, and let a small vibrato appear for the last few seconds.',
      'Keep the vibrato narrow, a shimmer rather than a wobble.',
      'Then try the reverse: start with vibrato and straighten the tone.',
      'Use the straight-then-vibrato version on the last word of a phrase in your song.',
    ],
    durationMin: 3,
    pattern: { kind: 'sustain', steps: [0], bpm: 30, startOffsetFromPassaggio: -3, stepUpSemitones: 2, repetitions: 4 },
  },
  {
    id: 'pentatonic-runs',
    name: 'Pentatonic runs, slow to fast',
    goal: 'Build clean, even runs by starting slowly and speeding up only when every note is clear.',
    helps: ['agility', 'pitchAccuracyCents'],
    steps: [
      'Sing 1-2-3-5-6-8-6-5-3-2-1 of the major pentatonic scale on "ah", one note per beat.',
      'Keep it light and quiet; runs are easier with less weight.',
      'When every note is clean, double the speed (two notes per beat), then try four.',
      'Aim for distinct notes, not a smear.',
      'Try the pattern on the last word of a phrase from your song.',
    ],
    durationMin: 4,
    pattern: { kind: 'scale', steps: [0, 2, 4, 7, 9, 12, 9, 7, 4, 2, 0], bpm: 90, startOffsetFromPassaggio: -9, stepUpSemitones: 1, repetitions: 4 },
  },
  {
    id: 'gospel-run-patterns',
    name: 'R&B and gospel run patterns',
    goal: 'Learn a short, idiomatic minor-pentatonic turn for tasteful runs at the ends of phrases.',
    helps: ['agility', 'pitchAccuracyCents'],
    steps: [
      'Learn the pattern 8-♭7-5-♭7-5-4-♭3-1 slowly on "oh", one note per beat.',
      'Lean very lightly on the first note and let the rest fall away.',
      'Double the speed only when every note is clear and in tune.',
      'Keep the volume low; a run is an ornament, not the main event.',
      'Place it on the last word of a phrase, and use one per section.',
    ],
    durationMin: 4,
    pattern: { kind: 'scale', steps: [12, 10, 7, 10, 7, 5, 3, 0], bpm: 100, startOffsetFromPassaggio: -9, stepUpSemitones: 1, repetitions: 4 },
  },
  {
    id: 'falsetto-flip-leap',
    name: 'Intentional flip (yodel leap)',
    goal: 'Switch deliberately from chest into falsetto on a leap, cleanly and in tune, as heard on R&B and soul hooks.',
    helps: ['flipsPerMinute', 'headInUpperRange', 'mixInUpperRange'],
    steps: [
      'On "oh-hoo", sing a comfortable low note in chest ("oh"), then leap up a major sixth into falsetto ("hoo").',
      'Let the voice flip audibly (that is the point), but land the top note in tune.',
      'Make the top note lighter and quieter than the bottom one.',
      'Come back down to the chest note and repeat.',
      'Then use a flip on the peak word of a hook.',
    ],
    durationMin: 3,
    pattern: { kind: 'arpeggio', steps: [0, 9, 0, 9, 0], bpm: 72, startOffsetFromPassaggio: -7, stepUpSemitones: 1, repetitions: 5 },
  },
  {
    id: 'blended-leap',
    name: 'Blended leap (no flip)',
    goal: 'Cross the same kind of leap without an audible break, for a connected mix.',
    helps: ['flipsPerMinute', 'mixInUpperRange', 'chestInUpperRange'],
    steps: [
      'Sing a comfortable low note on "nay" or "gee", then leap up a fifth on the same syllable.',
      'Lighten the bottom note slightly before the leap so there is less weight to carry up.',
      'Keep the vowel narrow and the volume level across the leap.',
      'If it breaks, sing it as a slide first, then shorten the slide little by little.',
      'As it smooths out, widen the leap to a sixth, then an octave.',
    ],
    durationMin: 3,
    pattern: { kind: 'arpeggio', steps: [0, 7, 0, 7, 0], bpm: 72, startOffsetFromPassaggio: -6, stepUpSemitones: 1, repetitions: 5 },
  },
  {
    id: 'soul-falsetto-forward',
    name: 'Forward soul falsetto',
    goal: 'Find a sweet, clear falsetto with forward, ringing placement, supported rather than breathy, for soul-style lead lines.',
    helps: ['headInUpperRange', 'brightness', 'breathiness', 'vibratoPresence'],
    steps: [
      'Find your falsetto (head voice, for higher voices) on a light "ng" hum a little above your passaggio.',
      'Open the "ng" to a bright "ee" or "ih", keeping the buzz in the front of your face.',
      'Sing a five-note scale in falsetto with steady airflow: a thin, clear line, not a sigh.',
      'Keep the volume soft to medium. The clarity comes from placement, not force.',
      'Try a falsetto line from a song: hold the last note straight, then let a small vibrato in.',
    ],
    durationMin: 4,
    pattern: { kind: 'scale', steps: MAJOR_FIVE_TONE, bpm: 96, startOffsetFromPassaggio: 2, stepUpSemitones: 1, repetitions: 4 },
  },
  {
    id: 'airy-falsetto-float',
    name: 'Airy falsetto float',
    goal: 'Float a soft, breathy falsetto for intimate hooks, with the air under control.',
    helps: ['headInUpperRange', 'breathiness', 'softOnsetRatio', 'dynamicRangeDb'],
    steps: [
      'Start with a quiet "h" and float a falsetto "hoo" a few notes above your passaggio.',
      'Let some air into the tone, but keep a clear pitch centre.',
      'Hold it for about four seconds at a quiet, even level, then glide down into your middle voice.',
      'Keep the mic or phone at your usual 20–30 cm, so this take compares fairly with your others.',
      'Stop and sip water if your throat feels dry.',
    ],
    durationMin: 3,
    pattern: { kind: 'sustain', steps: [0], bpm: 30, startOffsetFromPassaggio: 3, stepUpSemitones: 1, repetitions: 4 },
  },
  {
    id: 'drone-tuning',
    name: 'Sustain against a reference note',
    goal: 'Tighten pitch by holding notes against a steady reference and listening for the beating when you are off.',
    helps: ['pitchAccuracyCents', 'vibratoExtentCents'],
    steps: [
      'Play the note and listen to it for a moment before you sing.',
      'Sing it softly on "oo" and listen for a wobble (beating) between your voice and the tone. It disappears when you are in tune.',
      'Slide slowly just above and just below the note, then settle in the middle.',
      'Repeat on the third and fifth above it.',
      'Watch the live tuner readout if you have it open.',
    ],
    durationMin: 4,
    pattern: { kind: 'sustain', steps: [0, 4, 7], bpm: 40, startOffsetFromPassaggio: -5, stepUpSemitones: 2, repetitions: 3 },
  },
  {
    id: 'verse-chorus-build',
    name: 'Verse-to-chorus build',
    goal: 'Build intensity across a song section, from soft and speech-like to full and bright, without shouting.',
    helps: ['dynamicRangeDb', 'loudnessClimbDbPerSemitone', 'softOnsetRatio', 'brightness'],
    steps: [
      'Pick a verse and chorus from your song.',
      'Sing the verse at a relaxed speaking level, as if telling someone a story.',
      'Through the pre-chorus, add brightness and breath energy a step at a time.',
      'In the chorus, let the sound become full and forward, about as loud as an energetic conversation, not a shout.',
      'Record it. The chorus should sound bigger, but your throat should feel just as free.',
    ],
    durationMin: 5,
    cautions: ['If your throat tightens at the top, bring the chorus volume down and brighten the vowel instead.'],
  },
  {
    id: 'light-texture-onset',
    name: 'Light texture (optional)',
    goal: 'Add a hint of texture to one or two peak words, using a light vocal-fry onset at low volume and never squeezing.',
    helps: ['rasp'],
    steps: [
      'Only do this with a healthy, warmed-up voice. If you are hoarse, skip it.',
      'Make a quiet, relaxed vocal fry on "ah" (the creaky sound at the bottom of your speaking voice), with no effort.',
      'Keep your throat open with a "silent laugh" feeling, as if laughing without sound.',
      'Start a comfortable mid-range note from the fry and let it clear quickly into clean tone.',
      'Use it on one word only, at moderate volume. Five or six tries, then stop.',
    ],
    durationMin: 2,
    pattern: { kind: 'sustain', steps: [0], bpm: 40, startOffsetFromPassaggio: -8, stepUpSemitones: 1, repetitions: 3 },
    cautions: [
      'Stop at once if it hurts, tickles or makes you cough.',
      'Never make grit by squeezing or pressing your throat.',
      'Skip this completely if your voice is hoarse or tired, or if you are unsure. A clean tone suits all three singers.',
      'Keep it to a couple of minutes, and drink water.',
      'If hoarseness lasts two weeks or more, see an ENT doctor or laryngologist, ideally one who works with singers.',
      'If your voice suddenly cuts out or loses notes, stop, rest it and get it checked by a laryngologist within a few days.',
    ],
  },
];

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}
